/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inpis;

/**
 *
 * @author USER
 */
public class UI_Insert_Istri extends javax.swing.JFrame {

    /**
     * Creates new form UI_INSERT_ISTRI
     */
    public UI_Insert_Istri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_insert_istri = new javax.swing.JLabel();
        label_id_istri = new javax.swing.JLabel();
        label_nama_istri = new javax.swing.JLabel();
        label_nrp_istri = new javax.swing.JLabel();
        label_agama_istri = new javax.swing.JLabel();
        label_gol_darah_istri = new javax.swing.JLabel();
        label_hobby_istri = new javax.swing.JLabel();
        label_kpi_istri = new javax.swing.JLabel();
        label_kta_istri = new javax.swing.JLabel();
        label_kb_istri = new javax.swing.JLabel();
        label_pendidikan_terakhir_istri = new javax.swing.JLabel();
        label_ttl_istri = new javax.swing.JLabel();
        TextField_id_istri = new javax.swing.JTextField();
        TextField_nama_istri = new javax.swing.JTextField();
        TextField_nrp_istri = new javax.swing.JTextField();
        TextField_agama_istri = new javax.swing.JTextField();
        TextField_gol_darah_istri = new javax.swing.JTextField();
        TextField_hobby_istri = new javax.swing.JTextField();
        TextField_kpi_istri = new javax.swing.JTextField();
        TextField_kta_istri = new javax.swing.JTextField();
        TextField_kb_istri = new javax.swing.JTextField();
        TextField_pendidikan_terakhir_istri = new javax.swing.JTextField();
        TextField_ttl_istri = new javax.swing.JTextField();
        button_simpan_insert_istri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 112));
        setMinimumSize(new java.awt.Dimension(360, 112));
        setPreferredSize(new java.awt.Dimension(1800, 112));

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1004, 746));

        label_insert_istri.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        label_insert_istri.setText("DATA ISTRI");
        label_insert_istri.setMaximumSize(new java.awt.Dimension(262, 44));
        label_insert_istri.setMinimumSize(new java.awt.Dimension(262, 44));
        label_insert_istri.setPreferredSize(new java.awt.Dimension(262, 44));

        label_id_istri.setText("ID Istri :");

        label_nama_istri.setText("Nama Istri :");

        label_nrp_istri.setText("NRP :");

        label_agama_istri.setText("Agama Istri :");

        label_gol_darah_istri.setText("Golongan Darah Istri :");

        label_hobby_istri.setText("Hobby :");

        label_kpi_istri.setText("KPI Istri :");

        label_kta_istri.setText("KTA Jalansenastri :");

        label_kb_istri.setText("Metode KB :");

        label_pendidikan_terakhir_istri.setText("Pendidikan Terakhir Istri :");

        label_ttl_istri.setText("Tempta Tanggal Lahir Istri :");

        TextField_id_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        TextField_nama_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        TextField_nrp_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        TextField_agama_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        TextField_gol_darah_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        TextField_hobby_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        TextField_kpi_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        TextField_kta_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        TextField_kb_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        TextField_pendidikan_terakhir_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        TextField_ttl_istri.setPreferredSize(new java.awt.Dimension(400, 20));

        button_simpan_insert_istri.setText("Simpan");
        button_simpan_insert_istri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_simpan_insert_istriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_insert_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(button_simpan_insert_istri)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_kb_istri)
                                        .addComponent(label_pendidikan_terakhir_istri))
                                    .addGap(52, 52, 52))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_ttl_istri)
                                        .addComponent(label_kta_istri)
                                        .addComponent(label_kpi_istri)
                                        .addComponent(label_hobby_istri)
                                        .addComponent(label_gol_darah_istri)
                                        .addComponent(label_agama_istri)
                                        .addComponent(label_nrp_istri)
                                        .addComponent(label_nama_istri)
                                        .addComponent(label_id_istri))
                                    .addGap(42, 42, 42)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextField_ttl_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_kta_istri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_kpi_istri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_hobby_istri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_gol_darah_istri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_agama_istri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_nrp_istri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_nama_istri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_id_istri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextField_pendidikan_terakhir_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_kb_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_insert_istri, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_id_istri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_nama_istri)
                        .addGap(12, 12, 12)
                        .addComponent(label_nrp_istri)
                        .addGap(12, 12, 12)
                        .addComponent(label_agama_istri)
                        .addGap(12, 12, 12)
                        .addComponent(label_gol_darah_istri)
                        .addGap(12, 12, 12)
                        .addComponent(label_hobby_istri)
                        .addGap(12, 12, 12)
                        .addComponent(label_kpi_istri)
                        .addGap(12, 12, 12)
                        .addComponent(label_kta_istri)
                        .addGap(12, 12, 12)
                        .addComponent(label_kb_istri)
                        .addGap(12, 12, 12)
                        .addComponent(label_pendidikan_terakhir_istri)
                        .addGap(12, 12, 12)
                        .addComponent(label_ttl_istri))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TextField_id_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_nama_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_nrp_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_agama_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_gol_darah_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_hobby_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_kpi_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_kta_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_kb_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_pendidikan_terakhir_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_ttl_istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(button_simpan_insert_istri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_simpan_insert_istriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_simpan_insert_istriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_simpan_insert_istriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Istri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Istri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Istri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Istri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Insert_Istri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_agama_istri;
    private javax.swing.JTextField TextField_gol_darah_istri;
    private javax.swing.JTextField TextField_hobby_istri;
    private javax.swing.JTextField TextField_id_istri;
    private javax.swing.JTextField TextField_kb_istri;
    private javax.swing.JTextField TextField_kpi_istri;
    private javax.swing.JTextField TextField_kta_istri;
    private javax.swing.JTextField TextField_nama_istri;
    private javax.swing.JTextField TextField_nrp_istri;
    private javax.swing.JTextField TextField_pendidikan_terakhir_istri;
    private javax.swing.JTextField TextField_ttl_istri;
    private javax.swing.JButton button_simpan_insert_istri;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_agama_istri;
    private javax.swing.JLabel label_gol_darah_istri;
    private javax.swing.JLabel label_hobby_istri;
    private javax.swing.JLabel label_id_istri;
    private javax.swing.JLabel label_insert_istri;
    private javax.swing.JLabel label_kb_istri;
    private javax.swing.JLabel label_kpi_istri;
    private javax.swing.JLabel label_kta_istri;
    private javax.swing.JLabel label_nama_istri;
    private javax.swing.JLabel label_nrp_istri;
    private javax.swing.JLabel label_pendidikan_terakhir_istri;
    private javax.swing.JLabel label_ttl_istri;
    // End of variables declaration//GEN-END:variables
}
