/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inpis;

/**
 *
 * @author USER
 */
public class UI_Insert_TNI extends javax.swing.JPanel {

    /**
     * Creates new form UI_Insert_TNI
     */
    public UI_Insert_TNI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_data_personil = new javax.swing.JLabel();
        label_nama_personil = new javax.swing.JLabel();
        label_nrp_personil = new javax.swing.JLabel();
        label_asabri_personil = new javax.swing.JLabel();
        label_bpjs_personil = new javax.swing.JLabel();
        label_kta_personil = new javax.swing.JLabel();
        label_npwp_personil = new javax.swing.JLabel();
        label_telp_personil = new javax.swing.JLabel();
        label_agama_personil = new javax.swing.JLabel();
        label_alamat_personil = new javax.swing.JLabel();
        label_gol_darah_personil = new javax.swing.JLabel();
        label_jabatan_personil = new javax.swing.JLabel();
        label_korps_personil = new javax.swing.JLabel();
        label_pangkat_personil = new javax.swing.JLabel();
        label_pend_militer_personil = new javax.swing.JLabel();
        label_pend_pengembang_personil = new javax.swing.JLabel();
        label_pend_umum_personil = new javax.swing.JLabel();
        label_status_keluarga_personil = new javax.swing.JLabel();
        label_status_rumah_personil = new javax.swing.JLabel();
        label_tamat_jabatan_personil = new javax.swing.JLabel();
        label_tamat_tni_personil = new javax.swing.JLabel();
        label_ttl_personil = new javax.swing.JLabel();
        label_pangkat_pertama_personil = new javax.swing.JLabel();
        label_pangkat_terakhir_personil = new javax.swing.JLabel();
        TextField_nama_personil = new javax.swing.JTextField();
        TextField_nrp_personil = new javax.swing.JTextField();
        TextField_asabri_personil = new javax.swing.JTextField();
        TextField_bpjs_personil = new javax.swing.JTextField();
        TextField_kta_personil = new javax.swing.JTextField();
        TextField_npwp_personil = new javax.swing.JTextField();
        TextField_telp_personil = new javax.swing.JTextField();
        TextField_agama_personil = new javax.swing.JTextField();
        TextField_alamat_personil = new javax.swing.JTextField();
        TextField_gol_darah_personil = new javax.swing.JTextField();
        TextField_jabatan_personil = new javax.swing.JTextField();
        TextField_korps_personil = new javax.swing.JTextField();
        TextField_pangkat_personil = new javax.swing.JTextField();
        TextField_pend_militer_personil = new javax.swing.JTextField();
        TextField_pend_pengembang_personil = new javax.swing.JTextField();
        TextField_pend_umum_personil = new javax.swing.JTextField();
        TextField_status_keluarga_personil = new javax.swing.JTextField();
        TextField_status_rumah_personil = new javax.swing.JTextField();
        TextField_tamat_jabatan_personil = new javax.swing.JTextField();
        TextField_tamat_tni_personil = new javax.swing.JTextField();
        TextField_ttl_personil = new javax.swing.JTextField();
        TextField_pangkat_pertama_personil = new javax.swing.JTextField();
        TextField_pangkat_terakhir_personil = new javax.swing.JTextField();
        button_simpan_insert_personil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();

        label_data_personil.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        label_data_personil.setText("DATA PERSONIL");
        label_data_personil.setMaximumSize(new java.awt.Dimension(262, 44));
        label_data_personil.setPreferredSize(new java.awt.Dimension(262, 44));

        label_nama_personil.setText("Nama Personil :");

        label_nrp_personil.setText("NRP :");

        label_asabri_personil.setText("No Asabri :");

        label_bpjs_personil.setText("No. BPJS :");

        label_kta_personil.setText("No. KTA :");

        label_npwp_personil.setText("No. NPWP :");

        label_telp_personil.setText("No. Telepone");

        label_agama_personil.setText("Agama Personil :");

        label_alamat_personil.setText("Alamat Personil :");

        label_gol_darah_personil.setText("Golongan Darah Personil :");

        label_jabatan_personil.setText("Jabatan :");

        label_korps_personil.setText("Korps :");

        label_pangkat_personil.setText("Pangkat :");

        label_pend_militer_personil.setText("Pendidikan Militer :");

        label_pend_pengembang_personil.setText("Pendidikan Pengembang :");

        label_pend_umum_personil.setText("Pendidikan Umum :");

        label_status_keluarga_personil.setText("Status Keluarga :");

        label_status_rumah_personil.setText("Status Rumah :");

        label_tamat_jabatan_personil.setText("Tamat Jabatan :");

        label_tamat_tni_personil.setText("Tamat TNI :");

        label_ttl_personil.setText("Tempat Tanggal Lahir Personil :");

        label_pangkat_pertama_personil.setText("Tamat Pangkat Pertama :");

        label_pangkat_terakhir_personil.setText("Tamat Pangkat Terakhir :");

        TextField_nama_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_nrp_personil.setPreferredSize(new java.awt.Dimension(200, 20));
        TextField_nrp_personil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_nrp_personilActionPerformed(evt);
            }
        });

        TextField_asabri_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_bpjs_personil.setPreferredSize(new java.awt.Dimension(200, 20));
        TextField_bpjs_personil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_bpjs_personilActionPerformed(evt);
            }
        });

        TextField_kta_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_npwp_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_telp_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_agama_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_alamat_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_gol_darah_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_jabatan_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_korps_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_pangkat_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_pend_militer_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_pend_pengembang_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_pend_umum_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_status_keluarga_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_status_rumah_personil.setPreferredSize(new java.awt.Dimension(200, 20));
        TextField_status_rumah_personil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_status_rumah_personilActionPerformed(evt);
            }
        });

        TextField_tamat_jabatan_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_tamat_tni_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_ttl_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_pangkat_pertama_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        TextField_pangkat_terakhir_personil.setPreferredSize(new java.awt.Dimension(200, 20));

        button_simpan_insert_personil.setText("Simpan");
        button_simpan_insert_personil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_simpan_insert_personilActionPerformed(evt);
            }
        });

        jButton1.setText("Tambah Data Istri");

        jButton2.setText("Tambah Data Anak");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_data_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_simpan_insert_personil, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_pangkat_terakhir_personil)
                                .addComponent(label_pangkat_pertama_personil)
                                .addComponent(label_ttl_personil)
                                .addComponent(label_tamat_tni_personil)
                                .addComponent(label_tamat_jabatan_personil)
                                .addComponent(label_status_rumah_personil)
                                .addComponent(label_status_keluarga_personil)
                                .addComponent(label_pend_umum_personil)
                                .addComponent(label_pend_pengembang_personil)
                                .addComponent(label_pend_militer_personil)
                                .addComponent(label_pangkat_personil)
                                .addComponent(label_korps_personil)
                                .addComponent(label_jabatan_personil)
                                .addComponent(label_gol_darah_personil)
                                .addComponent(label_alamat_personil)
                                .addComponent(label_agama_personil)
                                .addComponent(label_telp_personil)
                                .addComponent(label_npwp_personil)
                                .addComponent(label_kta_personil)
                                .addComponent(label_bpjs_personil)
                                .addComponent(label_asabri_personil)
                                .addComponent(label_nrp_personil)
                                .addComponent(label_nama_personil))
                            .addGap(49, 49, 49)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextField_pangkat_terakhir_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_pangkat_pertama_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_ttl_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_tamat_tni_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_tamat_jabatan_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_status_rumah_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_status_keluarga_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_pend_umum_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_pend_pengembang_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_pend_militer_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_pangkat_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_korps_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_jabatan_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_gol_darah_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_alamat_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_agama_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_telp_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_npwp_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_kta_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_bpjs_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_asabri_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_nrp_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_nama_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_data_personil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_personil)
                    .addComponent(TextField_nama_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nrp_personil)
                    .addComponent(TextField_nrp_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_asabri_personil)
                    .addComponent(TextField_asabri_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_bpjs_personil)
                    .addComponent(TextField_bpjs_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_kta_personil)
                    .addComponent(TextField_kta_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_npwp_personil)
                    .addComponent(TextField_npwp_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_telp_personil)
                    .addComponent(TextField_telp_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_agama_personil)
                    .addComponent(TextField_agama_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_alamat_personil)
                    .addComponent(TextField_alamat_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_gol_darah_personil)
                    .addComponent(TextField_gol_darah_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_jabatan_personil)
                    .addComponent(TextField_jabatan_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_korps_personil)
                    .addComponent(TextField_korps_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_pangkat_personil)
                    .addComponent(TextField_pangkat_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_pend_militer_personil)
                    .addComponent(TextField_pend_militer_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_pend_pengembang_personil)
                    .addComponent(TextField_pend_pengembang_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_pend_umum_personil)
                    .addComponent(TextField_pend_umum_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_status_keluarga_personil)
                    .addComponent(TextField_status_keluarga_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_status_rumah_personil)
                    .addComponent(TextField_status_rumah_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tamat_jabatan_personil)
                    .addComponent(TextField_tamat_jabatan_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tamat_tni_personil)
                    .addComponent(TextField_tamat_tni_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ttl_personil)
                    .addComponent(TextField_ttl_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_pangkat_pertama_personil)
                    .addComponent(TextField_pangkat_pertama_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_pangkat_terakhir_personil)
                    .addComponent(TextField_pangkat_terakhir_personil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_simpan_insert_personil)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_simpan_insert_personilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_simpan_insert_personilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_simpan_insert_personilActionPerformed

    private void TextField_nrp_personilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_nrp_personilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_nrp_personilActionPerformed

    private void TextField_bpjs_personilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_bpjs_personilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_bpjs_personilActionPerformed

    private void TextField_status_rumah_personilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_status_rumah_personilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_status_rumah_personilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_agama_personil;
    private javax.swing.JTextField TextField_alamat_personil;
    private javax.swing.JTextField TextField_asabri_personil;
    private javax.swing.JTextField TextField_bpjs_personil;
    private javax.swing.JTextField TextField_gol_darah_personil;
    private javax.swing.JTextField TextField_jabatan_personil;
    private javax.swing.JTextField TextField_korps_personil;
    private javax.swing.JTextField TextField_kta_personil;
    private javax.swing.JTextField TextField_nama_personil;
    private javax.swing.JTextField TextField_npwp_personil;
    private javax.swing.JTextField TextField_nrp_personil;
    private javax.swing.JTextField TextField_pangkat_personil;
    private javax.swing.JTextField TextField_pangkat_pertama_personil;
    private javax.swing.JTextField TextField_pangkat_terakhir_personil;
    private javax.swing.JTextField TextField_pend_militer_personil;
    private javax.swing.JTextField TextField_pend_pengembang_personil;
    private javax.swing.JTextField TextField_pend_umum_personil;
    private javax.swing.JTextField TextField_status_keluarga_personil;
    private javax.swing.JTextField TextField_status_rumah_personil;
    private javax.swing.JTextField TextField_tamat_jabatan_personil;
    private javax.swing.JTextField TextField_tamat_tni_personil;
    private javax.swing.JTextField TextField_telp_personil;
    private javax.swing.JTextField TextField_ttl_personil;
    private javax.swing.JButton button_simpan_insert_personil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel label_agama_personil;
    private javax.swing.JLabel label_alamat_personil;
    private javax.swing.JLabel label_asabri_personil;
    private javax.swing.JLabel label_bpjs_personil;
    private javax.swing.JLabel label_data_personil;
    private javax.swing.JLabel label_gol_darah_personil;
    private javax.swing.JLabel label_jabatan_personil;
    private javax.swing.JLabel label_korps_personil;
    private javax.swing.JLabel label_kta_personil;
    private javax.swing.JLabel label_nama_personil;
    private javax.swing.JLabel label_npwp_personil;
    private javax.swing.JLabel label_nrp_personil;
    private javax.swing.JLabel label_pangkat_personil;
    private javax.swing.JLabel label_pangkat_pertama_personil;
    private javax.swing.JLabel label_pangkat_terakhir_personil;
    private javax.swing.JLabel label_pend_militer_personil;
    private javax.swing.JLabel label_pend_pengembang_personil;
    private javax.swing.JLabel label_pend_umum_personil;
    private javax.swing.JLabel label_status_keluarga_personil;
    private javax.swing.JLabel label_status_rumah_personil;
    private javax.swing.JLabel label_tamat_jabatan_personil;
    private javax.swing.JLabel label_tamat_tni_personil;
    private javax.swing.JLabel label_telp_personil;
    private javax.swing.JLabel label_ttl_personil;
    // End of variables declaration//GEN-END:variables
}
